routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'FeedController@index']);
Route::get('/latest-feeds', ['as' => 'latest-feeds', 'uses' => 'FeedController@index']);
Route::get('/feed-category/{feed_category}', ['as' => 'feeds.show.category', 'uses' => 'FeedController@showCategory']);


Route::get('/update', ['as' => 'feeds.update', 'uses' => 'FeedController@updateFeeds']);

Route::get('/login', ['as' => 'auth.login_form', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::get('/', ['as' => 'backend.dashboard', 'uses' => 'FeedSourceController@index']);

    Route::group(['prefix' => 'users'], function () {
        Route::get('/my-profile', ['as' => 'backend.users.profile-show', 'uses' => 'UserController@editProfile']);
        Route::put('/my-profile/save', ['as' => 'backend.users.profile-save', 'uses' => 'UserController@updateProfile']);
    });

    Route::group(['prefix' => 'feeds'], function () {

        Route::group(['prefix' => 'categories'], function () {
            Route::get('/', ['as' => 'backend.feed-categories.index', 'uses' => 'FeedCategoryController@index']);
            Route::get('/create', ['as' => 'backend.feed-categories.create', 'uses' => 'FeedCategoryController@create']);
            Route::post('/store', ['as' => 'backend.feed-categories.store', 'uses' => 'FeedCategoryController@store']);

            Route::get('/{id}/edit', ['as' => 'backend.feed-categories.edit', 'uses' => 'FeedCategoryController@edit']);
            Route::put('/{id}/update', ['as' => 'backend.feed-categories.update', 'uses' => 'FeedCategoryController@update']);
            Route::get('/{id}/delete', ['as' => 'backend.feed-categories.delete', 'uses' => 'FeedCategoryController@delete']);
        });

        Route::group(['prefix' => 'feed-urls'], function () {
            Route::get('/', ['as' => 'backend.feed-source.index', 'uses' => 'FeedSourceController@index']);
            Route::get('/create', ['as' => 'backend.feed-source.create', 'uses' => 'FeedSourceController@create']);
            Route::post('/store', ['as' => 'backend.feed-source.store', 'uses' => 'FeedSourceController@store']);
            Route::get('/{id}/edit', ['as' => 'backend.feed-source.edit', 'uses' => 'FeedSourceController@edit']);
            Route::put('/{id}/update', ['as' => 'backend.feed-source.update', 'uses' => 'FeedSourceController@update']);
            Route::get('/{id}/delete/', ['as' => 'backend.feed-source.delete', 'uses' => 'FeedSourceController@delete']);
        });
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Users full name; consists of first and last names attributes.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="robots" content="noindex, nofollow">

    <title>
        @yield('page-title')
    </title>

    <link rel="stylesheet" type="text/css" href="{{ asset('/assets/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/css/app.css') }}">

</head>
<body>
<div class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('backend.dashboard') }}">Dashboard</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        Feeds
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('backend.feed-categories.index') }}">Categories</a></li>
                        <li><a href="{{ route('backend.feed-source.index') }}">Urls</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ route('home') }}" target="_blank">View site</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <span class="glyphicon glyphicon-user"></span> {{ $active_user->full_name }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('backend.users.profile-show') }}">Edit profile</a></li>
                        <li><a href="{{ route('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>

    </div>
</div>

@if(\Session::has('alert'))
    <div class="system-alerts">
        <div class="container">
            @foreach(\Session::get('alert') as $type => $msg)
                <div class="alert alert-{{ $type }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ $msg }}
                </div>
            @endforeach
        </div>
    </div>
@endif

<div class="container">
    @yield('content')
</div>

<script src="{{ asset('/assets/js/jquery-3.1.1.min.js') }}"></script>
<script src="{{ asset('/assets/bootstrap/js/bootstrap.min.js') }}"></script>

</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="robots" content="noindex, nofollow">

    <title>
        @yield('page-title')
    </title>

    <link rel="stylesheet" type="text/css" href="{{ asset('/assets/bootstrap/css/bootstrap.min.css') }}">

</head>
<body>
<div class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <a class="navbar-brand" href="{{ route('home') }}">SeoFeeds</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ route('latest-feeds') }}">Latest feeds</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    @if(Auth::guest())
                        <a href="{{ route('auth.login') }}">Login</a>
                    @else
                        <a href="{{ route('backend.dashboard') }}" target="_blank">Dashboard</a>
                    @endif
                </li>
            </ul>
        </div>

    </div>
</div>

@if(\Session::has('alert'))
    <div class="system-alerts">
        <div class="container">
            @foreach(\Session::get('alert') as $type => $msg)
                <div class="alert alert-{{ $type }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ $msg }}
                </div>
            @endforeach
        </div>
    </div>
@endif

<div class="container">
    @yield('content')
</div>

<script src="{{ asset('/assets/js/jquery-3.1.1.min.js') }}"></script>
<script src="{{ asset('/assets/bootstrap/js/bootstrap.min.js') }}"></script>

@yield('scripts')

</body>
</html>